### ISSUE TITLE
Optionally disable gcFirst = TRUE

### ISSUE THREAD

**Issue by joshuaulrich** [romanzenka/RUnit#1]
I know the main reason you're maintaining RUnit is for backward compatibility / legacy applications, so I understand if this isn't something you want to add.  That said, it felt like my tests were taking too long to run, so I profiled my `runTestSuite()` call and found that 80%+ of the runtime was spent in `gc()`.  This is caused by the `gcFirst = TRUE` default of `system.time()`.

```diff
diff --git a/R/runit.r b/R/runit.r
index 89b8e51..0b37db0 100644
--- a/R/runit.r
+++ b/R/runit.r
@@ -196,7 +196,7 @@ isValidTestSuite <- function(testSuite)
   ## reset book keeping variables in RUnitEnv$.testLogger
   RUnitEnv$.testLogger$cleanup()
   ## ordinary test function execution:
-  timing <- try(system.time(func()))
+  timing <- try(system.time(func(), gcFirst = FALSE))
   if (inherits(timing, "try-error")) {
     if(RUnitEnv$.testLogger$isFailure()) {
       RUnitEnv$.testLogger$addFailure(testFuncName=funcName,
```

The entire test suite for the xts package went from a runtime of 20+ seconds to about 5 seconds after making the change above.  I don't necessarily think `gcFirst = FALSE` should be hard-coded, but it would be nice to make it an option.  Thoughts?

**Comment by romanzenka** [comment]
Great catch.

I think that a user of RUnit has following priorities:

1) Check that my code is correct
2) With minimum overhead
3) Let me optimize my tests if they are becoming pain

So the need for precise test timing is less important than the need for having the tests perform. The cheaper the tests, the more people will do them, the higher quality code.

My thinking is that we should disable gcFirst by default, but document and give an override for people working on large collections of tests so they do not end up optimizing tests that are really a GC run from a few tests before.

An even better solution would be to time GC separately from the test runtime, but I do not think you can actually do that in R.. you would have to hook into the GC somehow.

Looking at JUnit, they keep the entire suite of tests linked with strong references, so there is no garbage collection during the test run unless you explicitly do it as a programmer. I am not sure if that is a feature, looks more like a bug to me that could cause trouble to the programmer.

**Comment by joshuaulrich** [comment]
I agree with your prioritization.  I don't think users should be concerned about precise timings for unit tests, because separate benchmarks should be responsible for performance tests.  With the exception that they should care their unit tests run as quickly as possible.

I personally want to be able to iterate quickly while working on a feature or bug fix, and it's telling that the 25ms GC was taking 80%+ of my test execution time.  When it comes to benchmarks, I actually prefer that they take *more* time.  I could be optimizing something specific to my workstation if they run too quickly.

I can work on a patch to override the `gcFirst` value.  Any preference to how the user specifies it?  It could be passed via `...` from `runTestFile()` and/or set via `options()`.

How often do you think people optimize their tests for performance?  If done often, it might be useful to have a `profileTests()` function to profile each test independently.  It's not something I do often, unless it "feels" like tests take too long.

**Comment by romanzenka** [comment]
I'm already working on it. I will push into a new branch and you can check out if you like what you see.

I will be away from keyboard for about 12 days starting today so if we do not get it done, will you be okay with releasing when I am back?

I think people profile their tests only very rarely, when they absolutely must. I do not think anyone hardcodes "these tests must be faster than X" because timing is so unpredictable anyway, they will have very hard time having CRAN accept their packages if their tests rely on timing.

**Comment by romanzenka** [comment]
Check out [feature/disable-gc-for-timing](/romanzenka/RUnit/tree/feature/disable-gc-for-timing)

**Comment by joshuaulrich** [comment]
The diff looks good to me.  I'll pull the branch and test it in my workflow.  I don't mind if a release takes a couple weeks.  I can use the branch or my fork until then.

**Comment by romanzenka** [comment]
I am getting ready to release, cleaned up some issues reported by CRAN.

**Comment by romanzenka** [comment]
Package passed all tests, release created, submitted to CRAN.

**Comment by joshuaulrich** [comment]
Awesome, thank you!
