### ISSUE TITLE
Potential issue with  new as.data.frame.vector() method in R-devel

### ISSUE THREAD

**Issue by joshuaulrich** [romanzenka/RUnit#3]
[This line in checkFuncs.r](https://github.com/romanzenka/RUnit/blob/74014b8a4bb627a943da63aabe3052944f36586a/R/checkFuncs.r#L101) calls `as.vector()` on `target` and `current`. 

In R versions <=4.1.2, you can successfully call `checkEqualsNumeric()` with a one-column data.frame for both 'target' and 'current'. But will error in a near future version because `as.vector()` in R-devel has an `as.vector.data.frame()` method that returns a named list instead of a vector.

For example, this caused check failures in one of my packages:

```
d <- data.frame(V1 = 1:5)
checkEqualsNumeric(d, d)
Error in target == current : comparison of these types is not implemented
```

I fixed by changing the inputs to atomic vectors. But other users may have relied on this behavior too.

**Comment by romanzenka** [comment]
I will be releasing a maintenance update so I'll try to address this error for new versions of R.

**Comment by romanzenka** [comment]
I will be releasing 0.4.32 shortly which will contain this fix among others
